apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-mysql
  labels:
    app: {{ .Values.appLabel }}-mysql
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appLabel }}-mysql
  ports:
  - name: mysql
    protocol: TCP
    port: {{ .Values.mysql.service.port }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.serviceName }}-mysql-pvc
spec:
  accessModes: {{ .Values.mysql.primary.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.mysql.primary.persistence.size }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.serviceName }}-mysql
spec:
  replicas: {{ .Values.mysql.replicas }}
  serviceName: {{ .Values.serviceName }}-mysql
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Values.serviceName }}-mysql
        image: {{ .Values.mysql.image }}
        ports:
        - name: mysql
          protocol: TCP
          containerPort: {{ .Values.mysql.service.port }}
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
      labels:
        app: {{ .Values.appLabel }}-mysql
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi