apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-mysql
spec:
  selector:
    app: {{ .Values.serviceName }}-mysql
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: 3306
  type: {{ .Values.mysql.service.type }}