version: '3.8'

networks:
  networth:

services:

  eurekaserver:
    image: networth/eurekaserver:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - networth
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      EUREKA_INSTANCE_HOSTNAME: eurekaserver
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8071/

  gatewayserver:
    image: networth/gatewayserver:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - networth
    expose:
      - "8080"
    depends_on:
      - eurekaserver
      - configserver
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: gatewayserver
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/

  configserver:
    image: networth/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    networks:
      - networth
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: elizabeth.drew
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: glpat-aDw3wMCYyt5DVy8qaLU_

  user-service:
    image: networth/user-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    networks:
      - networth
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      - configserver
      - users_db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: user-service
      SPRING_DATASOURCE_URL: jdbc:mysql://users_db:3306/usersdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/

  users_db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=usersdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - networth
    volumes:
      - db_users:/var/lib/mysql



volumes:
  db_users:
