spring:
    cloud:
        kubernetes:
            discovery:
                enabled: true
                all-namespaces: true
            reload:
                enabled: true
        discovery:
            client:
                health-indicator:
                    enabled: false
    security:
        oauth2:
            resource-server:
                opaque-token:
                    client-secret: S7tTW9qIFn2sG6kzWNPJYkorHwPUCGgC
                    introspection-uri: http://keycloak:8080/realms/networth/protocol/openid-connect/token/introspect
                jwt:
                    jwk-set-uri: http://keycloak:8080/realms/networth/protocol/openid-connect/certs
                    issuer-uri: http://keycloak:8080/realms/networth

eureka:
    client:
        enabled: false