global:
  configMapName: common-configmap
  activeProfile: default

deploymentName: users-deployment
serviceName: users
appLabel: users
appName: users

replicaCount: 1

image:
  repository: networth/user-service
  tag: 0.0.1-SNAPSHOT

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
mysql_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true


mysql:
  databaseUser: admin
  databasePassword: password
  image: mysql:8.0
  replicas: 1
  service:
    type: ClusterIP
    port: 3306
  primary:
    persistence:
      enabled: true
      storageClass: "standard"
      accessModes:
        - ReadWriteOnce
      size: 8Gi