spring:
  application:
    name: "configserver"
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/wcdio_backendprojects/networth-tracker-configurations
          clone-on-start: true
          default-label: main
          username: elizabeth.drew
          password: glpat-aDw3wMCYyt5DVy8qaLU_

server:
  port: 8071

info:
  application:
    name: ${spring.application.name}
    description: Config Server For Networth Application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

logging:
  level:
    com:
      drew:
        config-server: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
