spring:
    kubernetes:
        all-namespaces: true
    cloud:
        kubernetes:
            discovery:
                discovery-server-url: http://spring-cloud-kubernetes-discoveryserver:80/
                enabled: true
            reload:
                enabled: true
        discovery:
            client:
                health-indicator:
                    enabled: false

eureka:
    client:
        enabled: false

keycloak:
    base-uri: http://keycloak
    keyUser:
        client-secret: Ow1dayvip5w4BHJeacRzVLHLCfJNCm3W