spring:
    cloud:
        kubernetes:
            discovery:
                all-namespaces: true
            reload:
                enabled: true
        discovery:
            client:
                health-indicator:
                    enabled: false
    datasource:
        url: jdbc:mysql://user-service_db:3306/user-servicedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: admin
        password: password

eureka:
    client:
        enabled: false

keycloak:
    base-uri: http://keycloak:8080
    keyUser:
        client-secret: cAVfmhFehqi9sJuPwfD5q7vSKd1e9rsy