spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://configserver:8071/"
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://users_db:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: password
  liquibase:
    contexts: default
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: none


javax:
  persistence:
    jdbc:
      driver: com.mysql.jdbc.Driver

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    com:
      drew:
        user-service: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  application:
    name: ${spring.application.name}
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0