spring:
    kubernetes:
        all-namespaces: true
    cloud:
        kubernetes:
            discovery:
                discovery-server-url: http://spring-cloud-kubernetes-discoveryserver:80/
                enabled: true
            reload:
                enabled: true
        discovery:
            client:
                health-indicator:
                    enabled: false

eureka:
    client:
        enabled: false

keycloak:
    base-uri: http://keycloak:8080
    keyUser:
        client-secret: cAVfmhFehqi9sJuPwfD5q7vSKd1e9rsy