app:
  image: networth/user-service:0.0.1-SNAPSHOT
  replicas: 1
  service:
    type: ClusterIP
    port: 8080
  env:
    - name: SPRING_DATASOURCE_URL
      value: jdbc:mysql://{{ template "mychart.fullname" . }}-mysql:3306/mydb
    - name: SPRING_DATASOURCE_USERNAME
      value: myuser
    - name: SPRING_DATASOURCE_PASSWORD
      value: mypassword
mysql:
  image: mysql:5.7
  replicas: 1
  service:
    type: ClusterIP
    port: 3306
  env:
    - name: MYSQL_ROOT_PASSWORD
      value: myrootpassword
    - name: MYSQL_DATABASE
      value: mydb
    - name: MYSQL_USER
      value: myuser
    - name: MYSQL_PASSWORD
      value: mypassword