{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.configMapName }}
data:
  {{- if .Values.settings.enabledFeatures.profile }}
  SPRING_PROFILES_ACTIVE: {{ .Values.app.activeProfile }}
  {{- end }}
  {{- if .Values.settings.enabledFeatures.mysql }}
  SPRING_DATASOURCE_URL: jdbc:mysql://{{ .Values.app.serviceName }}-mysql:3306/{{ .Values.app.serviceName }}db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: {{ .Values.mysql.databaseUser }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.databasePassword }}
  MYSQL_ROOT_PASSWORD: root_{{ .Values.mysql.databasePassword }}
  MYSQL_DATABASE: {{ .Values.app.serviceName }}db
  MYSQL_USER: {{ .Values.mysql.databaseUser }}
  MYSQL_PASSWORD: {{ .Values.mysql.databasePassword }}
  {{- end }}
  {{- if .Values.settings.enabledFeatures.configClient }}
  SPRING_CONFIG_IMPORT: {{ .Values.settings.config.serverURL }}
  SPRING_CLOUD_CONFIG_URI: {{ .Values.settings.config.uri }}
  {{- end }}
  {{- if .Values.settings.enabledFeatures.configServer }}
  SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: {{ .Values.configServer.username }}
  SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: {{ .Values.configServer.password }}
  {{- end }}
  {{- if .Values.settings.enabledFeatures.discovery }}
  SPRING.CLOUD.KUBERNETES.DISCOVERY.DISCOVERY-SERVER-URL: {{ .Values.settings.discoveryServerURL }}
  {{- end }}
  {{- if .Values.settings.enabledFeatures.gatewayServer }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: {{ .Values.settings.keycloak.url }}
  {{- end }}
  {{- end -}}