{{- define "common.mysql" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}-mysql
  labels:
    app: {{ .Values.app.label }}-mysql
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app: {{ .Values.app.label }}-mysql
  ports:
  - name: {{ .Values.app.label }}-mysql
    protocol: {{ .Values.mysql.service.protocol }}
    port: {{ .Values.mysql.service.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.serviceName }}-mysql
spec:
  replicas: {{ .Values.mysql.replicas }}
  serviceName: {{ .Values.app.serviceName }}-mysql
  selector:
    matchLabels:
      app: {{ .Values.app.label }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.app.label }}-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Values.app.serviceName }}-mysql
        image: {{ .Values.mysql.image }}
        ports:
        - name: {{ .Values.app.label }}-mysql
          protocol: {{ .Values.mysql.service.protocol }}
          containerPort: {{ .Values.mysql.service.port }}
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.configMapName }}
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.configMapName }}
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.configMapName }}
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.configMapName }}
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: {{ .Values.app.serviceName }}-mysql-pvc
          mountPath: /var/lib/mysql
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Delete
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.app.serviceName }}-mysql-pvc
    spec:
      storageClassName: {{ .Values.app.serviceName }}-retain-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.mysql.primary.persistence.size }}
  {{- end -}}