{{- define "common.mysql-pvc" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.serviceName }}-mysql-pvc
spec:
  accessModes: {{ .Values.mysql.primary.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.mysql.primary.persistence.size }}
  storageClassName: {{ .Values.mysql.primary.persistence.storageClass }}
{{- end -}}