{{- define "common.mysql" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}-mysql
  labels:
    app: {{ .Values.app.label }}-mysql
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app: {{ .Values.app.label }}-mysql
  ports:
    - name: mysql
      protocol: {{ .Values.mysql.service.protocol }}
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.serviceName }}-mysql
  labels:
    app: {{ .Values.app.label }}-mysql
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.label }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.app.label }}-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - name: mysql
              protocol: {{ .Values.mysql.service.protocol }}
              containerPort: {{ .Values.mysql.service.port }}
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configMapName }}
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configMapName }}
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configMapName }}
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configMapName }}
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: {{ .Values.app.serviceName }}-mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: {{ .Values.app.serviceName }}-mysql-data
          persistentVolumeClaim:
            claimName: {{ .Values.app.serviceName }}-mysql-pvc
  {{- end -}}