{{- define "common.storage" -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: {{ .Values.app.serviceName }}-retain-storage
provisioner: docker.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
{{- end -}}