spring:
  application:
    name: user-service
  output:
    ansi:
      enabled: always
  datasource:
    generate-unique-name: false
    name: mydatabase
    url: jdbc:mysql://test-service-mysql:3306/mydatabase
    username: admin
    password: password
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: none
