global: {}

app:
  name: account-service
  label: account-service
  deploymentName: account-service-deployment
  serviceName: account-service
  configMapName: account-service-configmap
  activeProfile: k8
  replicaCount: 1

settings:
  enabledFeatures:
    name: true
    profile: true
    mysql: true
    configClient: true
    configServer: false
    discovery: true
    securityServer: false
    otel: true
    kafka: true

image:
  repository: networth/account-service
  tag: 0.0.1-SNAPSHOT

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082
  containerPort: 8082

mysql:
  databaseUser: admin
  databasePassword: password
  replicas: 1
  image: mysql:8.0
  service:
    type: ClusterIP
    port: 3306
    protocol: TCP
  primary:
    persistence:
      enabled: true
      accessModes: ["ReadWriteOnce"]
      size: 8Gi