global:
  appConfig: {}

app:
  name: user-service
  label: users
  deploymentName: users-deployment
  serviceName: user-service
  configMapName: users-configmap
  activeProfile: k8
  config:
    uri: http://configserver:8071
    serverURL: optional:configserver:http://configserver:8071/
  discoveryServerURL: http://spring-cloud-kubernetes-discoveryserver:80/
  replicaCount: 1
  enabledFeatures:
    name: true
    profile: true
    mysql: true
    configClient: true
    configServer: false
    discovery: true
    resourceServer: false
    otel: true
    kafka: true

image:
  repository: networth/user-service
  tag: 0.0.1-SNAPSHOT

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081
  containerPort: 8081

mysql:
  databaseUser: admin
  databasePassword: password
  replicas: 1
  image: mysql:8.0
  service:
    type: ClusterIP
    port: 3306
    protocol: TCP
  primary:
    persistence:
      enabled: true
      accessModes: ["ReadWriteOnce"]
      size: 8Gi